# Generated by Django 3.0 on 2022-10-24 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Ujjain', 'Ujjain'), ('Sagar', 'Sagar'), ('Dewas', 'Dewas'), ('Satna', 'Satna'), ('Ratlam', 'Ratlam'), ('Rewa', 'Rewa'), ('Katni', 'Katni'), ('Singrauli', 'Singrauli'), ('Burhanpur', 'Burhanpur'), ('Khandwa', 'Khandwa'), ('Morena', 'Morena'), ('Bhind', 'Bhind'), ('Chhindwara', 'Chhindwara'), ('Guna', 'Guna'), ('Shivpuri', 'Shivpuri'), ('Vidisha', 'Vidisha'), ('Chhatarpur', 'Chhatarpur'), ('Damoh', 'Damoh'), ('Mandsaur', 'Mandsaur'), ('Khargone', 'Khargone'), ('Neemuch', 'Neemuch'), ('Pithampur', 'Pithampur'), ('Hoshangabad', 'Hoshangabad'), ('Itarsi', 'Itarsi'), ('Sehore', 'Sehore'), ('Betul', 'Betul'), ('Seoni', 'Seoni'), ('Datia', 'Datia'), ('Nagda', 'Nagda'), ('Dhanpuri', 'Dhanpuri'), ('Dhar', 'Dhar'), ('Balaghat', 'Balaghat')], max_length=100)),
                ('Zip_code', models.IntegerField()),
                ('state', models.CharField(default='Madhya Pradesh', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='media')),
                ('selling_price', models.IntegerField()),
                ('discription', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('WW', 'Winter Wear'), ('HA', 'Home Appliances'), ('L', 'Laptop')], max_length=30)),
                ('gender_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Ready To Ship', 'Ready To Ship'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=70)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
