# Generated by Django 3.0 on 2022-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
